"use client";

import { cn } from "@repo/design-system/lib/utils";
import dynamic from "next/dynamic";
import { parseAsString, useQueryState } from "nuqs";
import { useCallback, useEffect, useRef } from "react";
import { useAIQRGenerationCore } from "@/lib/hooks/use-ai-qr-generation-core";
import { useChatContext } from "@/lib/hooks/use-chat-context";
import { useGuards } from "@/lib/hooks/use-gaurds";
import { useAILocalDraftStore } from "@/store/ai-local-draft-store";
import type { AIPromptData } from "@/types/ai";
import { AIChatInput } from "./ai-chat-input";

const NoMessagesPlaceholder = dynamic(
  () =>
    import("./no-messages-placeholder").then(
      (mod) => mod.NoMessagesPlaceholder,
    ),
  { ssr: false },
);

interface AIChatPanelProps {
  onStyleGenerated?: () => void;
}

export function AIChatPanel({ onStyleGenerated }: AIChatPanelProps) {
  const { setPromptDraft } = useAILocalDraftStore();
  const { checkValidSession, checkValidSubscription } = useGuards();
  const hasAutoGeneratedRef = useRef(false);

  const [promptFromUrl, setPromptFromUrl] = useQueryState(
    "prompt",
    parseAsString.withDefault(""),
  );

  const { messages, startNewChat } = useChatContext();
  const { generateQRCore, isGenerating, cancelGeneration } =
    useAIQRGenerationCore();

  // Auto-generate when there's a prompt from URL
  useEffect(() => {
    if (
      promptFromUrl?.trim() &&
      !hasAutoGeneratedRef.current &&
      !isGenerating
    ) {
      hasAutoGeneratedRef.current = true;

      // Clear the prompt from URL
      setPromptFromUrl(null);

      // Check guards before generating
      if (!checkValidSession() || !checkValidSubscription()) {
        // Set the prompt to draft so user can see it in the input
        setPromptDraft(promptFromUrl);
        return;
      }

      // Auto-trigger generation
      generateQRCore({
        content: promptFromUrl,
        mentions: [],
      });
    }
  }, [
    promptFromUrl,
    setPromptFromUrl,
    isGenerating,
    generateQRCore,
    checkValidSession,
    checkValidSubscription,
    setPromptDraft,
  ]);

  const handleThemeGeneration = useCallback(
    async (promptData: AIPromptData) => {
      await generateQRCore(promptData);
      onStyleGenerated?.();
    },
    [generateQRCore, onStyleGenerated],
  );

  const handleNewChat = useCallback(() => {
    startNewChat();
  }, [startNewChat]);

  const hasMessages = messages.length > 0;

  return (
    <section className="@container relative isolate z-1 mx-auto flex size-full max-w-[49rem] flex-1 flex-col justify-center">
      <div
        className={cn(
          "relative flex size-full flex-1 flex-col overflow-hidden transition-all duration-300 ease-out",
        )}
      >
        {hasMessages ? (
          <div className="flex-1 space-y-4 overflow-y-auto p-4">
            {messages.map(
              (
                message: { parts: any[]; id: any; role: string },
                index: any,
              ) => {
                // Extract text content from message parts
                const textContent = message.parts
                  ?.filter((part: { type: string }) => part.type === "text")
                  .map((part: { type: string; text: any }) =>
                    part.type === "text" ? part.text : "",
                  )
                  .join("");

                return (
                  <div
                    key={message.id || index}
                    className={`flex ${message.role === "user" ? "justify-end" : "justify-start"}`}
                  >
                    <div
                      className={`max-w-[85%] rounded-lg px-3 py-2 text-sm ${
                        message.role === "user"
                          ? "bg-primary text-primary-foreground"
                          : "bg-muted"
                      }`}
                    >
                      {textContent}
                    </div>
                  </div>
                );
              },
            )}
            {isGenerating && (
              <div className="flex justify-start">
                <div className="bg-muted flex items-center gap-2 rounded-lg px-3 py-2 text-sm">
                  <div className="flex gap-1">
                    <span className="bg-foreground/30 size-2 animate-bounce rounded-full" />
                    <span
                      className="bg-foreground/30 size-2 animate-bounce rounded-full"
                      style={{ animationDelay: "0.1s" }}
                    />
                    <span
                      className="bg-foreground/30 size-2 animate-bounce rounded-full"
                      style={{ animationDelay: "0.2s" }}
                    />
                  </div>
                  <span className="text-muted-foreground">Generating...</span>
                </div>
              </div>
            )}
          </div>
        ) : (
          <div className="animate-in fade-in-50 zoom-in-95 relative isolate px-4 pt-8 duration-300 ease-out sm:pt-12 md:pt-16">
            <NoMessagesPlaceholder
              onGenerateTheme={handleThemeGeneration}
              isGeneratingTheme={isGenerating}
            />
          </div>
        )}
      </div>

      {/* Chat form input */}
      <div className="relative z-1 mx-auto w-full px-4 pb-4">
        <AIChatInput
          onThemeGeneration={handleThemeGeneration}
          isGeneratingTheme={isGenerating}
          onCancelThemeGeneration={cancelGeneration}
          onNewChat={handleNewChat}
          hasMessages={hasMessages}
        />
      </div>
    </section>
  );
}
